var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                               yy                          y    ",
   "               yy      yy                       yyyyyy                    y yyy ",
   "              yyyy   yyy                           yy                           ",
   "               yy                                                               ",
   "    yyy                           o      o                           xxx        ",
   "   yyyyyy                                                 xxx       xx!xx       ",
   "      yy                          x     xxx                         x!!!x       ",
   "                                  x!!!!!x                           xx!xx       ",
   "                               xxxxxxvxxx        xxx         xxx     xvx        ",
   "                      b                                                        x",
   "  xx              xxxxxxxx                o o          xx                      x",
   "  x                                      xxxxx                                 x",
   "  x                                                             o              x",
   "  x          xxxx                                 xxx           o          xxxxx",
   "  x  @       x         xxxxx                                                   x",
   "  xxxxxxxxxxxx      x         x   x   xxxxxxxxxxxxxxxxxxxx     xxx     x       x",
   "             x!!!!!!x!!!!!!!!!xo      x                  x     x x     xxxx    x",
   "             xxxxxxxxxxxxxxxxxxx      x                  x!!!!!x x!!!!!x       x",
   "                              x!!!!!!!x                  x!!!!!x x!!!!!x o     x",
   "                              xxxxxxxxx                  xxxxxxx xxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxx       xxxx                                x!x  ",
   "                                      x!!xxxxxxxxxx           xx             xx                              x!x  ",
   "                                      xx!!!!!!!!!!xx         xx               xx                             x!x  ",
   "                                       xxxxxxxxxx!!xxxxxxxxxx                                     o   o   o  x!x  ",
   "                                                xx!xxxx            o   o                                    xx!x  ",
   "                                                 x!xxxxxx                                     xxxxxxxxxxxxxxx!!x  ",
   "         yy                                      xvxxxxxxxxxxx     x   x                        !!!!!!!!!!!!!!xx  ",
   "      yyyyyyy                                   x   xxxxxxxxxxxx  |   |   |  xx            xxxxxxvxxxvxxxxvxxxxx  ",
   "       yyy                    yyy               x   x xxxxxxxxxxx!!!!!!!!!!!xx                                    ",
   "                            yyyy               x     x          xxxx!!!!!xxxx                                     ",
   "                                               x     x            xxxvxxx          xxx                            ",
   "                                               x     x                                   o                        ",
   "                                               x     x                                                            ",
   "                                               x     x                                   xx                       ",
   "                                               x     x                                   xx                       ",
   "                  b                            x     x      o o             xxxx        xxx                       ",
   "               xxxxxxx                         x     xx     x                            xx                       ",
   "              xx     xxx      xxx!!!!!!!!!!!!!!!!!!!!!x    xx                            xx                       ",
   "             xx       x!!x      xxx!!!!!!!!!!!!xxxxxxxx     x               xxxx        xxx                       ",
   "     @       x        x!!!xx       xxvxxxxxxxvxxx           x                            xx                       ",
   "    xxx      x         x!!!!x                              xx                            xx                       ",
   "    x x      x         x!!!!!xxxx                          xxxx         b              xxxx        xx             ",
   "!!!!x x!!!!!!x         x!!!!!x                         xx!!!!!!!!!!!!xxxxxx!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!x                       xx!!!!!!!xx!!!!!xxxxxx!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!x  o o o              xx!!!!!!xx !      xxxxx!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !     xxxx!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!xx        xxxxxxxxxxxxx!!!!!!xx   !     xxxxx!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !     xxxxxx!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !     xxxxxx!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                yyy                                                                                           ",
   "       yy     yyyyyy                                                                                          ",
   "      y                                   yy  yy                        yy yyy                                ",
   "                                       yyyyyyyy                        yyyyyyyyy              yyyy            ",
   "                                 yy  yyyyyy                                             yyyyyyyyyyy           ",
   "                                  yyyyyyy                                                 yyyyyyy             ",
   "                    yy                                                                       yy               ",
   "                  yyyyyy                                                                                      ",
   "                   yy                                                                                         ",
   "                                                                                                              ",
   "                                                  o                   xxx                                     ",
   "  yyyy yy                                         x                  x!!!x                                    ",
   "                                                         xxx          xxx                                     ",
   "                                                        x!!!x                                                 ",
   "                          o                 xxx          xxx                                                  ",
   "                          x                x!!!x                     o                                        ",
   "                                 xxx        xxx                      x                                        ",
   "                                x!!!x                   o                                                     ",
   "                    xxx          xxx                    x                  xxx                                ",
   "                   x!!!x                   o                              x!!!x                               ",
   "                    xxx                    x                   xxx         x!x                                ",
   "                                o                             x!!!x        xvx                                ",
   "                                x                xxx           xxx      xxx                                   ",
   "                                                x!!!x                xxx                                xxxxx ",
   "                                                 x!x              xxx                                   x   x ",
   "                                     xxx         xvx           xxx                                          x ",
   "                                    x!!!x                   xxx                                             x ",
   "                                     xxx                 xxx                                   o         o  x ",
   "                                                      xxx                                    xxxxxx   xxxxxxx ",
   "                                                   xxx                                       x              x ",
   "  xxx                                           xxx                                          x              x ",
   "  x x                                        xxx                                             x      x       x ",
   "  x                                       xxx                                                x             xx ",
   "  x                                    xxx                                                   x      o       x ",
   "  x = = =                           xxx                                                             x       x ",
   "  x                              xxx     o               b                                                  x ",
   "  x                      = = = xxx      xxxxx        xxxxxxx        xxxxx     xxxxxxxxxxxxxxxxxx|xxxxxxx|xxxx ",
   "  x                        xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   "  x                   o xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   "  x                  xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   "  x      @        xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                   xxx x      ",
   "                                                                                                       x      ",
   "                                                                                                       x      ",
   "                                                                                                       x      ",
   "                                                                                                       x      ",
   "                                                                                                       x      ",
   "                                                                                             o   o   o x      ",
   "                                                                                                     xx       ",
   "                    o                                         x   x  xxx  x    x   x     x xxx x    x  x  x   ",
   "                    x                                         x!!!x x!!!x x    x   x  o  x  x  xx   x  x  x   ",
   "                                                               x x  x!!!x x!!!!x   x  x  x  x  x!x  x  x  x   ",
   "                x   |   x                                 b     x   x!!!x  x!!xx   x!!x!!x  x  x!!x x         ",
   "                                                    x    xxxxxxxx!!!xxxx!!!!xx!x!!!!xxxxx!!xxx!x!!!xx!!x!!x!!!",
   "            x   |       |    x                                                                                ",
   "                                             xx                                                               ",
   "     o                                                                                                        ",
   "     xxx                          xxx                                                                         ",
   "                                                                                                              ",
   "                                                                                                             x",
   "                                                                                                             x",
   "                                xx                                                                           x",
   "                                x                                                                            x",
   "                                x                                                                            x",
   "                               xxx                                                                           x",
   "                              xxxxx                                 ||                                       x",
   "  xxxxxxxxxxx                 xxxxx                                                                   x      x",
   "  x         x o xxxxxxxxx o xxxxxxxxxx o xx                                                x                 x",
   "  x         x   x       x   xx       x   x                 ||                  x     x          x          o x",
   "  x  @      xxxxx   o   xxxxxx   o   xxxxx                                                                 x x",
   "  xxxxxxx                                     xxxxx      xx      xx     xxx             ||                   x",
   "   !!!!!x                                    =x!!!x                     xxx                        xxx       x",
   "   !!!!!xxxxxxxxxxxx!xxxxxxxxxxxx!xxxxxxxxxxxxx!!!x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
